name: .NET Core

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet builde ./src --configuration Release --no-restore
    - name: Test
      run: dotnet teste ./src --no-restore --verbosity normal
